# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))


# -- Project information -----------------------------------------------------
# ドキュメントサイトの概要を設定
project = '目次に戻る'
author = 'Hiroki'

# The full version, including alpha/beta/rc tags
release = '1.0.0'

# -- General configuration ---------------------------------------------------

# テーマの読み込み
import sphinx_rtd_theme

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# 拡張機能を追加
extensions = [
    'sphinx_rtd_theme',
    'recommonmark',
    'sphinx_markdown_tables',
    'sphinxcontrib.sqltable',
]

# 拡張子を設定
source_suffix = {
    '.rst': 'restructuredtext',
    '.md': 'markdown',
}

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# sphinxとreadthedocsのバージョン不整合に対処するために，目次ファイルを明示的に宣言
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
# 言語を設定
language = 'ja'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
# テーマを指定
html_theme = 'sphinx_rtd_theme'

# テーマのオプションを設定
html_theme_options = {
    'logo_only': False,
    'display_version': True,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': True,
    'style_nav_header_background': '#2980B9',
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': False,
    'navigation_depth': 3,
    'includehidden': True,
    'titles_only': False,
    'prev_next_buttons_location': None
}

# 各ノートのtitleタグがノート名になるように設定
html_title = ''

# ViewPageSourceの表示／非表示を設定
html_show_sourcelink = False

# 検索言語の設定
html_search_language = 'ja'

# 最新更新日のフォーマット
html_last_updated_fmt = '%Y-%m-%d'

# 著作権の表示/非表示
html_show_copyright = False

# Sphinxで生成したという文言の表示/非表示
html_show_sphinx = False

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# カスタムcssファイルのディレクトリを指定
html_static_path = ["_static"]
# カスタムcssファイルを読み込み
def setup(app):
    app.add_css_file('custom.css')